---
title: "R Notebook"
output: html_notebook
---

```{r}
library(survival)
library(survMisc)
library(gtools)
library(ggplot2)
library(dplyr)
```


```{r}
diabetic <- survival::diabetic
```


```{r}
km = survfit(Surv(time, status) ~ 1, conf.type="plain", data=diabetic)
summary(km)
plot(km)

km = survfit(Surv(time, status) ~ trt, conf.type="plain", data=diabetic)
summary(km)
plot(km, col=c("red","green"))
legend(50,1,unique(diabetic$trt),lty=1, col=c("red","green"),bty="n")
#plot(km, fun="cumhaz",xlab="Czas", ylab="Skumulowany hazard")

km1=survfit(Surv(time,status)~trt,conf.type="log", data=diabetic)
lines(km1, col="red")
km2=survfit(Surv(time,status)~trt,conf.type="log-log", data=diabetic)
lines(km2, col="green")

#estymator Nelsona-Aalena
Nels=survfit(Surv(time,status) ~ trt, conf.type ="log-log", type="fleming-harrington",data=diabetic) # estymator NA
summary(Nels)
lines(Nels,col="blue")
Nels2=survfit(Surv(time,status) ~ trt, conf.type ="plain", type="fleming-harrington",data=diabetic) # estymator NA
lines(Nels2,col="grey")

# wykres funkcji skumulowanego hazardu
plot(km1, fun="cumhaz",xlab="Czas", ylab="Skumulowany hazard")
lines(Nels2, fun="cumhaz",col="red")

# wykres funkcji trwania dla grup 
km = survfit(Surv(time, status) ~ eye, conf.type="plain", data=diabetic) # estymator KM
summary(km)
plot(km, col=c("red","green"))
legend(50,0.3,c("left","right"),lty=1, col=c("red","green"),bty="n")

diabetic$age_q <- quantcut(diabetic$age,q=4)

test=survdiff(Surv(time, status) ~ laser, data=diabetic, rho=1) # test Peto i Peto
test # wniosek: zmienna sex jest istotnym predyktorem (na poziomie istotności alfa=0,05)
test=survdiff(Surv(time, status) ~ laser, rho=0, data=diabetic) # test log-rank
test

test=survdiff(Surv(time, status) ~ age_q, data=diabetic, rho=1) # test Peto i Peto
test # wniosek: zmienna sex jest istotnym predyktorem (na poziomie istotności alfa=0,05)
test=survdiff(Surv(time, status) ~ age_q, rho=0, data=diabetic) # test log-rank
test

test=survdiff(Surv(time, status) ~ trt, data=diabetic, rho=1) # test Peto i Peto
test # wniosek: zmienna sex jest istotnym predyktorem (na poziomie istotności alfa=0,05)
test=survdiff(Surv(time, status) ~ trt, rho=0, data=diabetic) # test log-rank
test

test=survdiff(Surv(time, status) ~ risk, data=diabetic, rho=1) # test Peto i Peto
test # wniosek: zmienna sex jest istotnym predyktorem (na poziomie istotności alfa=0,05)
test=survdiff(Surv(time, status) ~ risk, rho=0, data=diabetic) # test log-rank
test

test=survdiff(Surv(time, status) ~ eye, data=diabetic, rho=1) # test Peto i Peto
test # wniosek: zmienna sex jest istotnym predyktorem (na poziomie istotności alfa=0,05)
test=survdiff(Surv(time, status) ~ eye, rho=0, data=diabetic) # test log-rank
test



Nels2=survfit(Surv(time, status) ~ trt, conf.type ="plain", type="fleming-harrington",data=diabetic) # estymator NA
lines(Nels2,col="grey")
```



```{r}
t1=survfit(Surv(time, status) ~ trt,data=diabetic)
comp(ten(t1),p=c(0,1,1,0.5,0.5),q=c(1,0,1,0.5,2)) # różne wagi w testach Fleminga-Harringtona
# jako druga lista w przypadku zmiennej dychotomicznej są wyświetlane testy Renyi
#kategoryzacja zmiennej według kwantyli i porównywanie krzywych przeżycia dla grup kwartylowych
t2 = ten(t1)
comp(t2,p=c(0,1,1,0.5,0.5),q=c(1,0,1,0.5,2))
b = attr(t2, "lrt") #lrw - obliczenia pomocnicze, lrt - test wilcoxona, sup - test supremum (kołmogorowa, typu reni), tft - testy dla trendu dla zmiennej w skali porządkowej
c = attr(t2, "sup")
cbind(b$W, b$pNorm, c$pSupBr)
```



```{r}
Cox=coxph(Surv(time, status)~laser+age+eye+trt+risk, data=diabetic)
summary(Cox)
library(MASS)
stepAIC(Cox,direction="backward")

Cox=coxph(Surv(time, status)~eye + trt + risk, data=diabetic)
summary(Cox)

rsq(Cox)

Prop=cox.zph(Cox,transform="identity") # weryfikacja za?o?enia proporcjonalno?ci
print(Prop)
plot(Prop)

#H0 - hazard jest proporcjonalny dla danej zmiennej w czasie

Prop=cox.zph(Cox,transform="rank") # weryfikacja za?o?enia proporcjonalno?ci
print(Prop)

Prop=cox.zph(Cox,transform="km") # weryfikacja za?o?enia proporcjonalno?ci
print(Prop)

reszty=resid(Cox, type="scaledsch") # graficzna weryfikacja za?o?enia proporcjonalno?ci
Time=as.numeric(rownames(reszty))
zmienne=c('eye','trt','risk')
for (i in 1:3) 
{plot(log(Time), reszty[,i], xlab="ln(Czas)",main=zmienne[i],
      ylab="Skalowane reszty Schoenfelda",pch=20, cex=0.7)
  lines( smooth.spline(log(Time), reszty[,i] ), lwd=3 )
}
```

```{r}
deviance=residuals(Cox,type="deviance")# jednostki odstaj?ce
s=Cox$linear.predictors
plot(s,deviance,xlab="Liniowy predyktor",ylab="Reszty odchyle?",cex=0.5, pch=20)
abline(h=3,lty=3)
diabetic$deviance=deviance
c1=which(diabetic$deviance>3)
```



```{r}
dfb=residuals(Cox,type="dfbeta")
n=dim(dfb)[1]
obs.nr=c(1:n)
for (j in 1:3) {
  plot(obs.nr,dfb[,j],xlab="Numer jednostki",ylab="Przyrost oceny parametru",
      main=zmienne[j])
  }
a1=which(dfb[,1]>(0.004)) #usun?? te jednostki
a2=which(abs(dfb[,2])>(0.06))
a3=which(abs(dfb[,3])>(0.1))
```

```{r}
c=sort(unique(c(a1,a2,a3,c1)))
dane1=diabetic[-c,] #zredukowany zbi?r
Cox2<-coxph(Surv(time, status)~eye + trt + risk, data=dane1)
stepAIC(Cox2,direction="backward")
```

